services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    networks:
      - tabnews

  database:
    image: postgres:16.0-alpine3.18
    container_name: "postgres-dev"
    env_file: .env.development
    ports:
      - 5432:5432
    networks:
      - tabnews

networks:
  tabnews:
    driver: bridge
